name: Build Moodle release ZIP

on:
  workflow_dispatch: # manual trigger
  push:
    tags:
      - 'v*.*-r*' # Run only on version tags like v4.1-r1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set plugin directory name
        run: echo "PLUGINNAME=course_checker" >> $GITHUB_ENV

      - name: Create Moodle-compatible ZIP
        run: |
          rsync -av --exclude='.git*' --exclude='tests/' --exclude='.github/' ./ ./${{ env.PLUGINNAME }}/
          zip -r ${{ env.PLUGINNAME }}.zip ${{ env.PLUGINNAME }}

      - name: Upload release ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PLUGINNAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
